### ISSUE TITLE
Leerzeichen fehlen

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#107]
'tschuldigung bitte Tim, dass der ganze Kram jetzt kommt, aber ich war selber krank und komme jetzt endlich zu einigen liegengebliebenen Sachen.

Bsp.:
https://familie-engels-briefe.de/briefe/A74B59
Johann Caspar Engels an Friedrich Engels, 12.11.1813

**Leerzeichen fehlt**:

dipl: Z. 11
Proclamationerlaßen
norm:
Proclamationerlaßen

Das Leerzeichen steht in
`</hi> <choice>`

TEI:
~~~
<hi rendition="#g.rend.script.latin">Proclamation</hi> <choice><orig>erlaßen</orig>
 <corr type="ortho">erlassen</corr>
 </choice>
~~~

dipl: Z. 16
auchDDorﬀ
norm:
AuchDDorff

Das Leerzeichen steht in
`</choice> <placeName ref="#place.duesseldorf" rendition="#g.rend.script.latin">`
~~~
<choice>
<orig>auch</orig>
 <corr type="ortho">Auch</corr>
 </choice> <placeName ref="#place.duesseldorf" rendition="#g.rend.script.latin">
 <choice>
<abbr>DDorﬀ</abbr>
 <expan n="no" cert="high" resp="#pers.ed.wernick-jana">D<ex>üſſel</ex>dorﬀ</expan>
</choice>
~~~
---
Leerzeichen fehlt in norm bei wegnormalisiertem **horizontalem Space**:

dipl: Z. 5
;[[SPACE]]angenehm
norm:
;angenehm

TEI:
``iﬅ;<space dim="horizontal" quantity="3" unit="char"/>angenehm``

**Comment by urummel** [comment]
Ich muss den issue leider wieder öffnen:

- In den Beispielen oben (Z. 11, Z. 16) fehlt das Leerzeichen jeweils weiterhin **in der diplomatischen Ansich**t. 
- **In der normalisierten Ansicht** fehlt jeweils ein Leerzeichen, wo in der diplomatischen Ansicht horizontaler whitespace (oben Bsp. Z. 5) angezeigt wird.

Kombiniert findet sich die Problematik in diesem Beispiel aus Brief:
https://familie-engels-briefe.de/briefe/DC5C79#diplomatisch

dipl Z. 13:
und Freündſchaft;	für mich L.Freündin,
norm:
und Freundschaft;für mich L. Freundin,

xml:
``und <choice><orig>Freünd<g ref="#enc.chardecl.ligatur.sch" resp="#pers.ed.hagenhoff-svenja">ſch</g>aft</orig><corr type="ortho">Freund<g ref="#enc.chardecl.ligatur.sch" resp="#pers.ed.hagenhoff-svenja">ſch</g>aft</corr></choice>;<space dim="horizontal" quantity="4" unit="char"/><anchor xml:id="mark.003.s"/>für mich <choice><abbr>L<am>.</am></abbr><expan n="no">L<ex>iebe</ex></expan></choice> <choice><orig>Freündin</orig><corr type="ortho">Freundin</corr></choice>,``

**Comment by thelfensdrfer** [comment]
Der neue Lösungsweg kommt vom Fabian und sollte zuverlässiger funktionieren?
