### ISSUE TITLE
Beispiel Kombination Hochstellung und Abkürzungszeichen

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#122]
Wegen eines Fehlers:

"Sie können familie-engels-briefe.de derzeit nicht aufrufen, da die Website HSTS verwendet. Netzwerkfehler und Angriffe sind in der Regel nur vorübergehend, sodass die Seite wahrscheinlich später wieder funktioniert."

kann ich die Seite im Moment nicht aufrufen.

Beispiele - wir sind eben nicht mehr dazu gekommen - für die Kombination **Hochstellung und Abkürzungszeichen** finden sich im Brief:

**071 Johann Engels an Friedrich Engels, 12. November 1813**

Wenn ich wieder auf die Seite komme, dann schaue ich mir die aktuelle Darstellung an.

**Comment by thelfensdrfer** [comment]
TODO: Ersten Buchstaben (statt letzten) doppelt unterstreichen
