### ISSUE TITLE
Expansion des Suspensionszeichens Typ 3 in normalisierter Ansicht

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#123]
https://familie-engels-briefe.de/briefe/C4258E#diplomatisch

Hier kommt es bei der Auflösung/Expansion des Suspensionszeichen Typ 3 zu einem Dopplung:

![SuspensionszeichenTyp3_dipl](https://user-images.githubusercontent.com/74976258/139147844-0559a682-39ee-4b43-8bef-f1ecc959edfb.jpg)

![SuspensionszeichenTyp3_norm](https://user-images.githubusercontent.com/74976258/139147883-1628c418-909d-4102-b74f-896116b030d3.jpg)

**Comment by thelfensdrfer** [comment]
Hier fehlt bei dem `expan` Element ein `n="no"` wenn ich das richtig sehe?

**Comment by thelfensdrfer** [comment]
Geklärt: type=suspension immer anzeigen
