### ISSUE TITLE
Scans werden nicht geladen

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#136]
https://familie-engels-briefe.de/briefe/49182F?highlight=general#diplomatisch

Bilder werden nicht geladen.

**Comment by thelfensdrfer** [comment]
2 von den 3 Facsimiles gibt es in den Daten die du mir geschickt hast, allerdings sind die nicht korrekt benannt. Ich kann die manuell umbenennen, hier müssen wir dann aber aufpassen das das nicht öfter passiert (ist)?

**Comment by thelfensdrfer** [comment]
Um das etwas zu präzisieren: Die TIFF Dateien habe ich einmalig in JPG konvertiert. TIFF Dateien können theoretisch mehrere Seiten enthalten, JPG nicht. In den Fällen hängt das Script an die JPG Dateien ein `_1` bzw. `_x` an. Normalerweise funktioniert das, bei genau diesen Facsimiles gab es mehrere Seiten und das hat deswegen nicht funktioniert:

```
FE_157.1_25021818_1.jpg
FE_157.2_25021818_1.jpg
FE_175.1_02101818_1.jpg
FE_175.2_02101818_1.jpg
FE_175.3_02101818_1.jpg
FE_175.4_02101818_1.jpg
FE_185.1_15121818_1.jpg
FE_185.2_15121818_1.jpg
FE_185.3_15121818_1.jpg
FE_185.4_15121818_1.jpg
FE_188.1_30121818_1.jpg
FE_188.2_30121818_1.jpg
FE_188.3_30121818_1.jpg
FE_188.4_30121818_1.jpg
FE_224.1_28021820_1.jpg
FE_224.2_28021820_1.jpg
FE_224.3_28021820_1.jpg
FE_224.4_28021820_1.jpg
FE_233.1_16061820_1.jpg
FE_233.2_16061820_1.jpg
FE_233.3_16061820_1.jpg
FE_234.1_27071820_1.jpg
FE_234.2_27071820_1.jpg
FE_234.3_27071820_1.jpg
FE_234.4_27071820_1.jpg
FE_251.1_03011822_1.jpg
FE_251.2_03011822_1.jpg
FE_251.3_03011822_1.jpg
FE_251.4_03011822_1.jpg
FE_265.1_31051823_1.jpg
FE_265.2_31051823_1.jpg
FE_265.3_31051823_1.jpg
FE_265.4_31051823_1.jpg
FE_274.1_18071823_1.jpg
FE_274.2_18071823_1.jpg
FE_274.3_18071823_1.jpg
FE_274.4_18071823_1.jpg
FE_295.1_16081827_1.jpg
FE_295.2_16081827_1.jpg
FE_295.3_16081827_1.jpg
FE_295.4_16081827_1.jpg
```

Im Nachhinein fällt mir auf das ich die auch nicht manuell umbenennen kann, da sonst Informationen verloren gehen (alle Seiten nach der 1.).

**Comment by urummel** [comment]
Im oben von mir angemerkten Brief und alle in deiner Liste (DANKE!) zeigen jetzt die richtigen Scans an. Ich denke, du brauchst nichts umbenennen. Sollte ich jetzt noch Fehler mit nicht angezeigten Scans finden, dann kenne ich jetzt verschiedene Fehlerquellen, die ich beheben kann.
RUND KLAMMERN sollten allerdings nicht in den Dateinamen "bei dir" vorkommen.

**Comment by thelfensdrfer** [comment]
Die werde ich dann manuell löschen, stören aber auch nicht.

**Comment by urummel** [comment]
Ah, ich dachte, die müssten stören, da bei uns in den Daten keine runden Klammern vorkommen in den Referenzen.

**Comment by thelfensdrfer** [comment]
Das stimmt zwar, aber die gibt es dann doppelt. Einmal mit Klammern und einmal mit Unterstrich.

**Comment by urummel** [comment]
Ja gut, dann :-)
