### ISSUE TITLE
Brief kann nicht angezeigt werden

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#141]
https://familie-engels-briefe.de/briefe/355951#normalisiert

wird nicht angezeigt.
Fehlermeldung:

"Einige Daten konnte nicht geladen werden! Probiere es bitte später noch einmal oder schreibe uns eine E-Mail."

**Comment by thelfensdrfer** [comment]
Der versuch statt Brief 043, den Brief 043b zu laden. Ich gucke mir mal an warum das so ist.

**Comment by urummel** [comment]
Der nicht lädt ist ``xml:id="fe.045"``

**Comment by thelfensdrfer** [comment]
Der versucht aber Brief 043b zu laden. Wahrscheinlich steht irgendwo was falsches. Ich gucke mir aber mal genau an warum genau dieser Brief versucht wird zu laden.

**Comment by thelfensdrfer** [comment]
Neh das ist eindeutig 043b. So wird das vorher umgewandelt:

```
043a CF7D02 
043b 355951 
044 BFF82D 
045 E46D0A 
```

Aber das wurde tatsächlich bei mir an einer Stelle noch nicht berücksichtigt. Sollte jetzt funktionieren!
