### ISSUE TITLE
Eigentlich nur eine Frage: CMS?

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#142]
Für Seiten wie "Editorischer Bericht" unter "Projekt" war doch die Einbindung eines Content Management Systems vorgesehen, oder? Welches ist das und wie sind die Zugangsdaten?

**Comment by thelfensdrfer** [comment]
Eine super Frage, da haben Herr Lukas und ich uns letzte Woche drüber unterhalten. Ich habe dir auch bereits ein Konto erstellt, scheinbar werden die Mails nicht versendet.

Der Link zur Anmeldung ist: https://wordpress.familie-engels-briefe.de/wp-admin/

Die Zugangsdaten schicke ich dir in einer separaten Mail. Morgen kann ich dir das auch kurz zeigen/erklären.
