### ISSUE TITLE
eXist-Datenbank 8443 nicht erreichbar

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#144]
Fehlermeldung:

Failed to write request: Connect to chost20.zim.uni-wuppertal.de:8443 [chost20.zim.uni-wuppertal.de/132.195.130.150] failed: Connection refused: connect (https://chost20.zim.uni-wuppertal.de:8443/xmlrpc)

Könnte ein Neustart helfen?

**Comment by thelfensdrfer** [comment]
Ist neu gestartet, funktioniert es wieder?

**Comment by urummel** [comment]
Ja! Merci.
