### ISSUE TITLE
Alternative Lesung: Darstellung in grau

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#145]
Leider doch noch ein neuer Issue:

es geht um die Darstellung des Inhalts des Elements `<unclear>` in der **normalisierten Ansicht**:

https://familie-engels-briefe.de/briefe/A74B59#normalisiert

![fe071_wolle_wolte](https://user-images.githubusercontent.com/74976258/142904269-d61dc136-1f08-4a5e-bb6e-070a341f3650.jpg)

`<choice><unclear cert="high" reason="illegible" resp="#pers.ed.rummel-ulrich">wolle</unclear><unclear cert="medium" reason="illegible" resp="#pers.ed.rummel-ulrich">wolte</unclear></choice>`

Dargestellt werden soll in der **normalisierten Ansicht** **nur** die wahrscheinlichere Lesung `@cert="high"` in der **normalen Schriftfarbe** (d.h. schwarz).

In der **diplomatischen Ansicht** wird das richtige Wort korrekt grau dargestellt.

**Comment by thelfensdrfer** [comment]
Analog zur diplomatischen Ansicht zeige ich jetzt jeweils das "sicherste" Element an. Wenn es sehr wahrscheinlich das richtige Element ist, "high", dann auch in der normalen Schriftfarbe.

**Comment by urummel** [comment]
Prima.
