### ISSUE TITLE
Strophen und Zeilen eines Gedichts im Brief

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#154]
Es tut mir leid, hier kommt noch etwas:

Im Brief fe156
Johann Keetman, Osnabrück, an Friedrich Engels, Düsseldorf, 29. und 30.1.1818 (Brief)

haben wir den seltenen Fall der Elmente `<lg>` und `<l>` für Strophen und Zeilen von Gedichten. Dabei ist `<lg>` ähnlich `<p>` zu behandeln. Die Zeilen `<l>` sollen in beisen Ansichten stabil bleiben, d.h. nicht umbrochen werden.

``<lg>
                        <l rendition="#g.enc.tagsdecl.indent-large"><anchor xml:id="annot.002.s"/>Es gefellt mir nummen Eine</l>
                        <l rendition="#g.enc.tagsdecl.indent-large">Un ſelle gefallt mir gewiß</l>
                        <l rendition="#g.enc.tagsdecl.indent-large">Sie iﬅ ſo flink und dunders<space rend="unclear"/>nett</l>	
                        <l rendition="#g.enc.tagsdecl.indent-large">O wann <g cert="high" ref="#enc.chardecl.variant.minuscule-ij-i" resp="#pers.ed.hagenhoff-svenja">J</g> nur das Maidli hätt’</l>
                        <l rendition="#g.enc.tagsdecl.indent-large"><g cert="high" ref="#g.enc.chardecl.variant.capital-ij-i" resp="#pers.ed.hagenhoff-svenja">J</g> wär im Paradies.</l>
                        <l><space dim="horizontal" quantity="19" unit="char"/><g ref="#enc.chardecl.distinct.horizontaldash">-----</g></l>
                    </lg>
                    <lg>
                        <l rendition="#g.enc.tagsdecl.indent-large">’S’iſch wohr, das Maidli gefallt mir</l>
                        <l rendition="#g.enc.tagsdecl.indent-large">Unds Maidli hätt i gern</l>
                        <l rendition="#g.enc.tagsdecl.indent-large">S’h<subst xml:id="annot.004"><del rend="overwritten">ä</del><add>a</add></subst>t allewil e frohe Mueth</l>
                        <l rendition="#g.enc.tagsdecl.indent-large">Unds Geſichtle hats wie Milch und Bluet</l>
                        <l rendition="#g.enc.tagsdecl.indent-large">Und Auge wiane Stern!</l>
                        <l><space dim="horizontal" quantity="20" unit="char"/><g ref="#enc.chardecl.distinct.horizontaldash">-----</g></l>
                    </lg>
                    <lg>
                        <l rendition="#g.enc.tagsdecl.indent-large">Und wann i’s ſeh vo witem</l>
                        <l rendition="#g.enc.tagsdecl.indent-large">Steigts Bluet mir ins Geſicht</l>
                        <l rendition="#g.enc.tagsdecl.indent-large">Es wird mir um das Herz ſo chnapp</l>
                        <l rendition="#g.enc.tagsdecl.indent-large">Unds Wa<g ref="#enc.chardecl.ligatur.ss" resp="#pers.ed.hagenhoff-svenja">ſſ</g>er lauft mir die Backen ’nab,</l>
                        <l rendition="#g.enc.tagsdecl.indent-large">Weiß nit wie mir geſchicht.<anchor xml:id="annot.002.e"/></l>
                        <l><space dim="horizontal" quantity="23" unit="char"/><g ref="#enc.chardecl.distinct.horizontaldash">-----</g></l>
                    </lg>
                </lg>``

**Comment by urummel** [comment]
Sorry, das muss ich als letztes anmerken:

Hier habe ich mich wahrscheinlich nicht deutlich ausgedrückt.

Die **Zeilen** und **Strophen** sollen **auch in der normalisierten Ansicht erhalten** bleiben wie in der diplomatischen Ansicht. Alle anderen Unterschiede zwischen norm und dipl wie immer.

**Comment by thelfensdrfer** [comment]
Achso, beisen=beiden. Ja das hätte ich mir denken können, ich dachte das wäre irgendein germanistischer Begriff...
