### ISSUE TITLE
Ligaturen

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#16]
Es wäre einfacher wenn das `data-rendition` Attribut schon bei dem `tei_choice` Element auftauchen würde, nicht erst bei `tei_abbr`. Dadurch kann man je nach `type` entscheiden ob entweder `tei_abbr` oder `tei_expan` angezeigt werden soll.

## Original

```html
<span class="tei_choice">
    <span class="tei_abbr" data-rendition="#g.enc.tagsdecl.suspension.type2" data-type="suspension">
        [...]
    </span>
    <span class="tei_expan">
        [...]
    </span>
</span>
```

## Vorschlag

```html
<span class="tei_choice" data-rendition="#g.enc.tagsdecl.suspension.type2">
    <span class="tei_abbr" data-type="suspension">
        [...]
    </span>
    <span class="tei_expan">
        [...]
    </span>
</span>
```

**Comment by thelfensdrfer** [comment]
Das gleiche gilt eigentlich für alles was mit `tei_choice` zu tun hat.

* [ ] `tei_orig`/`tei_corr` bzw. `tei_abbr`/`tei_expan`
* [ ] Alle relevanten data Attribute, z.B. `data-type`, `data-rendition`

Wenn die Attribute schon bei `tei_choice` bekannt wären, könnte man basierend darauf die Darstellung anpassen.

**Comment by FabianEtling** [comment]
Grundsätzlich beziehen sich die Attribute schon immer genau auf die Inhalte des Elements, in welchem sie gesetzt sind: D. h. die Attribute, die zur Beschreibung der grafischen Ausprägung des vorgefundenen Textes (z. B. `@rendition`) in `<abbr>` auftauchen, gelten für die Abbreviation und nicht für die Expansion, usw.
Insb. in Fällen, wo die durch `<choice>` gekennzeichnete "Auswahl" unterschiedliche Lesungen - also von verschiedenen Editor*innen angelegte abweichende Transkriptionen - beschreibt (s. folgendes Beispiel), ist eine Verallgemeinerung und Übertragung der Attribute in das `<choice>`-Element nicht möglich.

Beispiel "alternative Lesung", hier Unklarheit bzgl. der Schreiberhand:

```
<choice>
  <unclear cert="high" rendition="#rend.hand.friedrich-engels-senior">irgendeine Anmerkung</unclear>
  <unclear cert="medium" rendition="#rend.hand.friedrich-engels-junior">irgendeine Anmerkung</unclear>
</choice>
```


Realisierbar wäre höchstens eine "Typisierung" des `<choice>`-Elements - das ist aber redundante Information, da dies ja bereits aus den enthaltenen Elementen abzuleiten ist. Falls es die Verarbeitung erleichtert, ließe sich das problemlos implementieren.
