### ISSUE TITLE
Ersetzung von span.sup mit sup Element

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#17]
Es gibt für Subscript und Superscript schon die entsprechenden HTML Elemente. Die bräuchte man nicht stylen und wären semantisch besser geeignet.

Siehe:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup bzw.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sub

**Comment by FabianEtling** [comment]
Die Information habe ich bewusst auch in der HTML-Ausgabe wieder in ein Attribut übertragen. Im TEI kann die Hoch- bzw. Tiefstellung über das globale Attribut `@rend` quasi in jedem Element hinterlegt werden - also auch theoretisch in Elementen, die z. B. bereits mit einer inhaltlichen Semantik belegt sind (fiktives Bsp.: `<date rend="sup">5. Januar</date>`). 

Die sup/sub-Elemente könnte man theoretisch zusätzlich generieren - um valides HTML zu gewährleisten und das Markup der Ausgabe einfach zu halten (und z. B. das Generieren diverser sup/sub-Elemente bei komplexeren Verschachtelungen von Elementen zu vermeiden), halte ich es (vom theoretischen Standpunkt aus) für sinnvoller, das CSS-Styling hier vom Attribut anstatt vom Element abhängig zu machen.

**Comment by thelfensdrfer** [comment]
Alles klar :+1:
