### ISSUE TITLE
Kennzeichnung von Textverlust

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#18]
Bei 1.7.1 hast du `damage -> supplied` mit eckigen Klammern gekennzeichnet: `Äußerlich ist es aber nun ungemein unruhig hier [mein] Bester!`

Bei 1.7.2 nicht: `meinen Brief aus Boulogne nicht`, müsste das nicht heißen `meinen Brief a[us Bou]logne nicht`?

**Comment by FabianEtling** [comment]
Hier sind zwei Aspekte zu unterscheiden:

1. diplomatische vs. normalisierte Darstellung
2. Zeichen vorhanden (an einem anderen Ort) vs. Zeichen nicht vorhanden (und rekonstruiert)


Die Satzbeispiele in der Synopse sind jeweils korrekt:

Fall "Textverlust, Zeichen durch Editor*in rekonstruiert":
- Diplomatisch: Nur Angabe, dass Text verloren ist (nur der vorgefundene Zeichenbestand wird auch abgebildet)
- Normalisiert: Angabe des rekonstruierten Textes, aber explizite Kennzeichnung als "Editortext" durch eckige Klammern und Kursivierung

Fall "Textverlust, Zeichen an anderem Ort vorgefunden":
- Diplomatisch: Abbildung der an anderem Ort vorgefundenen, ursprünglich dort stehenden Zeichen, als "Einfügung" gekennzeichnet durch spitze Klammern
- Normalisiert: Abbildung der an anderem Ort vorgefundenen Zeichen ohne Kennzeichnung (da es sich um Autorentext handelt)
