### ISSUE TITLE
Anzeige von Abbreviation in "Hoch- und Tiefstellung von Zeichen"

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#19]
Normalerweise wird in der normalisierten Darstellung ja entweder die Abbreviation oder der expandierte Text angezeigt. In dem Beispiel 1.9.3 aber beides?

```xml
<choice>
     <abbr>7<hi rend="sup">ber</hi></abbr>
     <expan n="com">September</expan>
</choice>
```

![image](https://user-images.githubusercontent.com/699106/97434491-5ffc8f80-191f-11eb-9044-d52768ded897.png)

**Comment by FabianEtling** [comment]
Hier handelt es sich um den Spezialfall der "erläuternden Expansion" (vgl. 1.10.2.4). Die Abkürzung soll hierbei erhalten bleiben, für die bessere Verständlichkeit jedoch zusätzlich als Editortext (also in eckigen Klammern und kursiviert) expandiert werden.

Die Angabe im Markup erfolgt über das Attribut `n="com"`.
