### ISSUE TITLE
HTML Klasse von Closer Elementen

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#20]
Semantisch würde es meiner Meinung nach mehr Sinn machen das sowohl `tei_closer` als auch `tei_closer_inline` die gleiche Klasse, also `tei_closer` hätten. Bei `tei_closer_inline` gibt es ja bereits das zusätzliche Attribut `data-rend="inline"`.

Das ist aber eine Geschmacksfrage und nicht besonders wichtig.

**Comment by FabianEtling** [comment]
Das stimmt. Derzeit taucht `tei_closer` als Klasse immer dann auf, wenn das zugehörige Element eine Blockstruktur bildet und tei_closer_inline, wenn der "Closer" innerhalb eines Absatzes identifiziert wurde. Das wird allerdings in der HTML-Ausgabe auch durch `<p>` und `<span>` (und über das zusätzliche Attribut `data-rend="inline"`) repräsentiert.

Wenn `tei_closer` als einheitliche Klasse benötigt wird, dann ändere ich das ab.

**Comment by thelfensdrfer** [comment]
Nein, benötigt wird das nicht. War nur eine Idee.
