### ISSUE TITLE
Editornotizen

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#22]
Aus der Synopse, 3.12.1 "Positionierung am Briefende mit Editornotiz". Woher kommt die Notiz?

**Comment by FabianEtling** [comment]
Hier ist noch zu klären, wie die "Editornotiz" genau ausfallen soll. Diese lässt sich dann vmtl. im XSLT anhand des jeweiligen Kontext generieren. Vorerst reicht eine Dummy-Notiz (z. B. "Anmerkung:" - wenn sich ohne Aufwand Seite und Position auslesen lassen, dann ggf. auch "Anmerkung auf Seite <`./preceding::span[@class='tei_pb']/@data-n`>, <`@data-place`>:").
