### ISSUE TITLE
Supsensiio Beispiel 3

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#26]
In dem dritten Beispiel für Punkt **1.3.1.4 Suspensionszeichen** steht `Hagen 5 Jan.∮` mit einem Kurvenintegral am Ende? Ist das ein Tippfehler oder woher kommt das Zeichen? Im HTML Code in der diplomatischen Ansicht und im XML Code taucht es nicht auf.

**Comment by FabianEtling** [comment]
Die drei Typen von Suspensionszeichen sollen durch jeweils ein spezifisches Zeichen repräsentiert werden. Dafür wurden die folgenden Zeichen ausgewählt:

Beispiel (Typ 1):
[…] Den beﬅen Seg**ƺ**. Gottes nach dem äuß**ƺ** und inern Menſchen […]

Beispiel (Typ 2):
[…] 150 D:z Lang**ℓ**. und 600 ﬅük ganz Brochirte […]

Beispiel (Typ 3):
Hagen 5 Jan.**∮** […]

Die Zeichen sind also so gewollt und werden derzeit im XSLT für die diplomatische Ausgabe generiert.

**Comment by thelfensdrfer** [comment]
Stimmt, mein Fehler. Im orignal tauchen die auf.
