### ISSUE TITLE
2.2 Umstellungen

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#27]
Aus dem Beispiel in der diplomatischen Ansicht v1.0.0:

```
[...]
Liebe
<span class="tei_metamark" data-function="insertion" data-place="above" data-rendition="#enc.tagsdecl.metamark.numeral-underlined" data-target="#txt.perm002.a" data-id="txt.perm002.m"></span> 
<span class="tei_metamark" data-function="separator" data-place="inline" data-rendition="#enc.tagsdecl.metamark.perm001">|</span>
[...]
```
Hier fehlt links neben dem `|` eine 1, oder soll ich die aus dem `txt.perm002.m` manuell extrahieren?

**Comment by FabianEtling** [comment]
Die '1' ist transkribiert als Teil des Metazeichens und sollte innerhalb von `span.tei_metamark` auch ausgegeben werden. Der Fehler lag im XSLT.

Fixed.
