### ISSUE TITLE
Darstellung mancher Unicode Zeichen

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#28]
Manche Unicode Zeichen werden nicht korrekt dargestellt. Konkret habe ich jetzt ein Beispiel aus "3.12.1 Nicht-lineare Verteilung von Textsegmenten i. Allg." gefunden. Das bezieht sich auf Brief `fe295.xml`, konkret auf das Zeichen nach dem Text: `Um deine Briefe mache kein Couvert mehr ???`.

Andere Zeichen, z.B. ↙, funktionieren Problemlos. Das hängt wahrscheinlich vom Font ab. Wichtig ist hier glaub ich einfach das Zeichen verwendet werden die bei den System-Standard-Schriften inklusidert sind. Welche das genau sind hängt aber leider ja von dem jeweiligen System ab. Oder wir suchen für die Zeichen alternative Icons, siehe https://fontawesome.com/icons?d=gallery (z.B. https://fontawesome.com/icons?d=gallery&q=arrow), die ich dann automatisiert ersetzen würde.

**Comment by urummel** [comment]
Wir können in diesem Fall auf ein kleines 'q' wechseln in der Auszeichnung, hier zweimal unterstrichen und im Text hochgestellt. Ich werde das entsprechend auszeichnen. Im Moment komme ich nicht an die Daten. Es scheint irgendeinen Server- oder Datenbankfehler zu geben.

**Comment by thelfensdrfer** [comment]
Ok. Solange das dann in den Daten korrigiert wird brauche ich das ja auf meiner Seite nicht zu ändern.
