### ISSUE TITLE
Pseudonymisierung von MitarbeiterInnendaten

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#31]
Aktuell sieht man öffentlich in der XML und HTML Darstellung wer wann an welcher Datei gearbeitet hat.

**Comment by urummel** [comment]
Gute Frage (was auch sonst!), ich muss bei Fabian bzw. Herrn Lukas abfragen, was geplant ist und ob Zustimmungen eingeholt worden sind.
