### ISSUE TITLE
Testing: Bevorzugter Browser?

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#34]
Sollte ich beim Testing einen bestimmten Browser verwenden?

Ich benutze zur Zeit Chrome und Firefox (jeweils aktuell) (unter Windows 8.1. Windows 10 wäre auch möglich).

**Comment by thelfensdrfer** [comment]
Ganz im Gegenteil. Am besten, aber nicht zwingend notwendig, wäre es wenn du zufällige/beliebige Browser verwendest. Programmiert wird hier immer mit der neusten JavaScript Version, auch wenn die nur von sehr wenigen Browsern unterstützt wird. Daher wird der Programmcode nach der Programmierung noch in eine möglichst kompatible Version übersetzt, dafür kann man eigene Regeln definiern. Um so weniger Browser unterstützt werden, desto schlanker (schnellere Ausführung und geringere Downloadzeit) ist die Anwendung für die Browser die noch funktionieren. Bei modernen Anwendungen sagt man das die von mindestens 95-97.5% unterstützt werden sollte. Da das ja eine Anwendung ist die hauptsächlich von "technikfremden" Personen genutzt werden wird, dachte ich mir das 99% ein guter Wert ist. Das heißt das die Familie Engels Website auf 99% der aktuellsten Browser funktionieren sollte. Hier eine aktuelle List (die Liste ändert sich natürlich mit der Zeit):

- and_chr 87
- and_ff 83
- and_qq 10.4
- and_uc 12.12
- android 81
- baidu 7.12
- chrome 87
- chrome 86
- edge 87
- edge 86
- firefox 83
- firefox 82
- ie 11
- ios_saf 14.0-14.2
- ios_saf 13.4-13.7
- ios_saf 12.2-12.4
- kaios 2.5
- op_mini all
- op_mob 59
- opera 72
- opera 71
- safari 14
- safari 13.1
- samsung 13.0
- samsung 12.0

`and` steht hier für Android. Das Betriebssystem ist egal, außer bei den mobilen Varianten.
