### ISSUE TITLE
Registerdetailseite: Was angezeigt werden soll

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#36]
Wenn ich das richtig verstanden habe, werden noch die Details aus den Registern
reg_global_pers.xml
reg_global_org.xml
reg_global_place.xml
 angezeigt. Die globalen Register werden demnächst noch weiter gefüttert.

Zusätzlich schlage ich für die Personen vor (jeweils gesteuert über die GND, Bsp. Fr. Engels jun.):
- Link auf den Eintrag zur GND auf 'Deutsche Nationalbibliothek' (realisiert)
- Link auf die  Übersichtsseite zur jeweiligen Person auf 'Deutsche Biographie':
https://www.deutsche-biographie.de/pnd118530380.html#indexcontent
- Link auf die Übersicht zur Person auf dieser Personensuchmaschine:
http://persondata.toolforge.org/p/gnd/118530380
- Link auf die Ergebnisseite des 'Beacon-Findbuchs (PND/BEACON AKS)'
http://beacon.findbuch.de/seealso/pnd-aks?format=redirect&id=118530380

**Comment by thelfensdrfer** [comment]
Genau, die 3 Registerdateien werden zusammen mit den Briefen synchronisiert.

**Comment by thelfensdrfer** [comment]
Siehe: https://storybook.familie-engels-briefe.de/?path=/story/register-person--default
