### ISSUE TITLE
Suspensionsschleifen werden nicht angezeigt

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#37]
Bsp: Brief 004, S. 2, Zeile 2
<abbr rendition="#g.enc.tagsdecl.suspension.type1" type="suspension">Luﬅbarkeit</abbr>

Die Auflösung in der normalisierten Ansicht zu Lustbarkeiten mit -en klappt.

**Comment by thelfensdrfer** [comment]
Bei mir wird das wie folgt angezeigt, wird das bei dir anders angezeigt oder stimmt die Anzeige bei mir auch nicht?

![Screenshot from 2020-12-14 13-39-42](https://user-images.githubusercontent.com/699106/102082231-dc84f800-3e11-11eb-9134-e846db2487d5.png)

Für mich als Referenz:

```html
<span data-rendition="#g.enc.tagsdecl.suspension.type1" data-type="suspension" class="tei_abbr"><span data-topicid="mark.002" data-type="R" class="engels_topic"><span data-topicid="mark.004" data-type="L" class="engels_topic">Luﬅbarkeit</span></span><span class="suspensionGlyph">ƺ</span></span>
```

**Comment by urummel** [comment]
Deine Anzeige ist korrekt. Bei mir sieht es so aus (Firefox, Chrome, Edge unter Windows 8.1 sowie im chrome unter Android):

![Screenshot_FehlSuspZeichen_20201214](https://user-images.githubusercontent.com/74976258/102084297-42bf4a00-3e15-11eb-87ca-1f9b32f23b72.jpg)

**Comment by thelfensdrfer** [comment]
Das kommt aktuell aus der diplomatischen HTML Ansicht an:

```
<span class="tei_choice">
    <span class="tei_abbr" data-rendition="#g.enc.tagsdecl.suspension.type1" data-type="suspension">
        <span class="engels_topic" data-topicId="mark.002" data-type="R">
            <span class="engels_topic" data-topicId="mark.004" data-type="L">Lustbarkeit</span>
        </span>
    </span>
    <span class="tei_expan" data-resp="#pers.ed.klar-jasmine">
        <span class="engels_topic" data-topicId="mark.002" data-type="R">
            <span class="engels_topic" data-topicId="mark.004" data-type="L">Lustbarkeit</span>
        </span>
        <span class="tei_ex">
            <span class="engels_topic" data-topicId="mark.002" data-type="R">
                <span class="engels_topic" data-topicId="mark.004" data-type="L">en</span>
            </span>
        </span>
        <span class="engels_topic" data-topicId="mark.002" data-type="R">
            <span class="engels_topic" data-topicId="mark.004" data-type="L"></span>
        </span>
    </span>
</span>
```

@FabianEtling Mein Screenshot ist von einer zwischengespeicherten Version von vor ein paar Tagen/Wochen, hat sich da was geändert?
