### ISSUE TITLE
Frage: In welchem Turnus werden die angezeigten Daten aktualisiert?

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#38]
Wenn ich Änderungen an den XML/TEI-Files vornehme, in welchem Turnus werden die Daten auf der Website aktualisiert? Kann ich das steuern?

**Comment by thelfensdrfer** [comment]
Aktuell werden die Daten nur auf Anfragen synchronisiert. Ich habe dir gerade ein Passwort geschickt, du kannst dich damit auf https://api.familie-engels-briefe.de/ anmelden. Wenn du oben auf "SYNC" klickst, wird dir angezeigt wann das letzte mal synchronisiert wurde. Ich würde dich bitten aktuell NICHT auf den "Sync" Button auf dieser Seite zu klicken...Was normalerweise passiert:

- Die Daten aus der API werden zwischengespeichert
- Bei einem Klick auf den Button wird dieser Cache gelöscht und die Daten neu synchronisiert
- Dann wird der Cache wieder neu aufgebaut

Die Synchronisierung dauert aktuell aber ein paar Minuten, daher kommt es vor das der Browser einen Fehler anzeigt und die Daten nicht komplett synchronisiert werden. Das wäre jetzt auch nicht tragisch, aber bis ich reagieren kann zeigt die Website unvollständige oder keine Daten an. Zukünftig soll man das über die API Seite jederzeit selbst erledigen können.

**Comment by thelfensdrfer** [comment]
Die Letzte Synchronisierung war vor 4 Wochen, soll ich die noch einmal anstoßen? Ich könnte das z.B. auch erst einmal wöchentlich machen bis die Funktion funktioniert?

**Comment by urummel** [comment]
Einmal wöchentlich wäre erstmal gut. Aber ganz nach deinem Zeitplan, es besteht keine Dringlichkeit. Ich sammle ja noch Unstimmigkeiten und korrigieren hier und da mal in den Daten. Die Wirkung kann ich dann bei Gelegenheit überprüfen.
