### ISSUE TITLE
Lang-s ('ſ') und Ligaturen ('ſt', 'ſſ', 'ff' etc.) werden nicht dargestellt

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#39]
Diplomatische Ansicht: Die Ligaturen ('ſt', 'ſſ', 'ff' etc.) und ganz allgemein das Lang-s ('ſ'') werden nicht dargestellt (Bsp. Brief 005).

**Comment by thelfensdrfer** [comment]
Hast du da ein sehr konkretes Beispiel aus Brief 005? Dann prüfe ich für das Beispiel einmal nach was genau aus dem XML/HTML ankommt.

**Comment by urummel** [comment]
Beispiele für langes s, also ſ , und für die Ligaturen ſt ( &#xFB05; ) ſſ.
...aus der provisorischen diplomatischen Ansicht, Brief 005, Zeile 7. Die Schrift gibt dort keine Ligaturen her, aber sie ist ausgezeichnet im TEI/XML.

![Screenshot_Lang_s_und_Ligaturen_20201217](https://user-images.githubusercontent.com/74976258/102542418-0eb48500-40b2-11eb-8c0e-d6cfb1b24a2d.jpg)


wi<g ref="#enc.chardecl.ligatur.ss" resp="#pers.ed.biehl-christian">ſſ</g>en nicht, was gut i&#xFB05; – ; inde<g ref="#enc.chardecl.ligatur.ss" resp="#pers.ed.biehl-christian">ſſ</g>en hätte ich ſehr gewünſcht,

**Comment by thelfensdrfer** [comment]
@FabianEtling Kannst du hier mal nach gucken. Im XML steht:

```xml
Doch wie ich oben ſagte: wir wi<g ref=\"#enc.chardecl.ligatur.ss\" resp=\"#pers.ed.biehl-christian\">ſſ</g>en nicht, was gut iﬅ –.
```

Daraus wird aber in der diplomatischen Ansicht:
```html
doch wir wi<span xmlns:v="http://exist-db.org/versioning" class="tei_g" data-ref="#enc.chardecl.ligatur.ss" data-resp="#pers.ed.biehl-christian">ss</span>en nicht, was gut ist – ;
```
