### ISSUE TITLE
Bilder und Texte für Registereinträge

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#4]
Klärung von Bildrechten von den Registereinträgen (z.B. von Personen und Orten) um diese anzeigen zu können.

**Funktionen:**

- [x] Eigene Seiten für Registereinträge
- [x] Laden von passenden Bildern aus Wordpress
- [x] Ergänzung von Daten aus z.B. https://portal.dnb.de/
- [x] Verlinkung von Registereinträgen in Briefen

**Comment by urummel** [comment]
Es gibt Bilder, die wir für die Museumspräsentation ausgewählt haben und für die auch die Rechte geklärt sind bzw. die gemeinfrei sind.

Das betrifft
1. einen Teil der Briefschreiber*innen (die Kernfamilie, die Abbildungen stammen aus dem Engelshaus und sind meines Wissens auch für die Website lizensiert)
2. einen Teil der Orte (lizensiert bzw. gemeinfrei)
3. einige Themen (Religion, Reisen, Liebe; lizensiert bzw. gemeinfrei)

**Comment by urummel** [comment]
Welche Pixelmaße brauchen wir? Ich kann die vorhandenen Bilder entsprechend bearbeitet zusammenstellen.

**Comment by thelfensdrfer** [comment]
Bearbeitet werden müssen die Bilder nicht. Wenn man die Bilder später in Wordpress hochlädt, werden dort automatisch skalierte Versionen der Bilder erstellt.

**Comment by thelfensdrfer** [comment]
@urummel ich hab vorhin mit Fabian über den Punkt gesprochen. Das die Bilder in Wordpress hochgeladen werden fanden wir beide gut. Aber für die zukünftige Vollständigkeit der Daten würden wir eher empfehlen die redaktionellen Texte und Beschreibungen der Registereinträge in die jeweiligen TEI Dateien zu schreiben, oder was sagst du dazu?

Die Bilder können wir weiterhin in Wordpress speichern und die würde ich dann automatisiert im Frontend laden und neben dem Text anzeigen.

**Comment by urummel** [comment]
Wir haben darüber ja auch per E-Mail geschrieben. Da war irgendwie der Wurm drin. 

Also, ich meine definitiv, dass die Inhalte zu den Personen etc. aus unseren Registereinträgen kommen sollten. Dafür machen wir die ja und dann haben sie auch eine gleichbleibende Qualität.

Was ich gut fände, wäre eine Nutzung der in den Registerdaten hinterlegten Normdaten, z. B. indem Links angeboten werden wie diese:

https://persondata.toolforge.org/p/gnd/118530380
und
https://www.deutsche-biographie.de/pnd118530380.html#indexcontent

wobei es mir nicht um die Lebensdaten zur Person geht, sondern um dort vorhandene und dynamisch fortgeschriebene Verknüpfungen mit **weiteren** Datenquellen.
