### ISSUE TITLE
Inline-Opener: Leerzeichen danach

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#40]
Bsp: Brief 005: 
Ansicht norm und dipl:
Es fehlt ein Leerzeichen nach dem Inline-Opener:

"Mein werther Freund!ich habe [...]"

<opener rend="inline">
                       <salute>Mein werther <rs type="person" ref="#pers.partic.engels-johann-caspar-II" resp="#pers.ed.biehl-christian">Freund</rs>!</salute>
                </opener>
                <p>ich habe [...]</p>

**Comment by thelfensdrfer** [comment]
Das muss im TEI geändert werden. Aktuell gibt es in dem konkreten Fall keinen Absatz nach dem Inline Opener im HTML. @FabianEtling kannst du dir das mal angucken?

Das XML:

```xml
<opener rend="inline">
    <salute>Mein werther <rs type="person" ref="#pers.partic.engels-johann-caspar-II" resp="#pers.ed.biehl-christian">Freund</rs>!</salute>
</opener>
<p>ich habe Ihre beÿden[...]</p>
```

Wird zu:

```html
<span class="tei_salute">Mein werther <span><div data-v-70596efa="" aria-describedby="tooltip" class="inline"><span data-v-70596efa="" class="tooltip-button">Freund</span><div data-v-70596efa="" role="tooltip" class="tooltip-content" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(934px, 512px); display: none;" data-popper-placement="bottom"><div data-v-70596efa="">Johann Caspar  Engels</div><div data-v-70596efa="" class="mt-4"><a data-v-70596efa="" href="/register/person/pers.partic.engels-johann-caspar-II" class="underline text-sm uppercase">Mehr Informationen</a></div></div></div></span>!</span>ich habe Ihre beÿden 
```

allerdings fehlt hier das Leerzeichen vor `ich habe`.

**Comment by thelfensdrfer** [comment]
@urummel Das muss in den Quelldaten korrigiert werden. Hier gibt es innerhalb der Elemente kein Leerzeichen nach dem `Freund!`. Also entweder muss dort oder vor `ich habe` ein Leerzeichen eingefügt werden.
