### ISSUE TITLE
Normalisierte Ansicht: Einzüge

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#41]
In der Ansicht norm: Es erhalten den Standardeinzug:

- jeder Absatz
- im Opener, die Anrede, auch im Falle einer Inline-Anrede (dann Einzug der ganzen ersten Zeile),
- im Closer: jedes Element, das **keine** besondere Auszeichnung zur Räumlichkeit trägt.

**Comment by thelfensdrfer** [comment]
Das heißt es werden folgende Elemente eingerückt?

* [ ] Absätze `<p>`
* [ ] Opener `<opener>`
* [ ] Close `<closer>`

Ich weiß nur nicht ob ich aktuell den letzten Punkt umsetzen kann, also die Einrückung bei **keiner** besonderen Auszeichnung. Denn genau diese sind immer irgendwo innerhalb des Elementes versteckt. Einfacher wäre hier wenn man das Element mit einem Attribut versehen könnten.

Ich habe mich bisher auch an die Synpose gehalten, dort wird beschrieben das **nur** die diplomatische Ansicht einen Einzug erhalten soll? Siehe Punkt 3.11 https://static.familie-engels-briefe.de/erl/ERL_Synopse.htm Dort sind die Einzüge im HTML auch speziell gekennzeichnet. Siehe beispielsweise https://familie-engels-briefe.de/briefe/006#diplomatic

**Comment by urummel** [comment]
in der Synopse steht grün unterlegt: 
- Es wird ein Standardeinzug gesetzt.
- Auch für ‚negative‘ Einzüge wird der ‚positive‘ Standardeinzug gesetzt.
- Anm.: Absätze ohne Einzug im Original werden ebenfalls mit Standardeinzug gesetzt.

Das Beispiel in der Synopse ist nicht eindeutig, aber relativ zum Wort 'Beispiel' haben die beiden Zeilen einen Einzug ;-)

Mit dem letzten Punkt oben ist gemeint:

<closer> bekommt den Standardeinzug, wenn nicht ausgezeichnet mit dem Attribut und Attributwert <closer rend="inline">
<salute> bekommt den Standardeinzug, wenn es auf einer neuen Zeile steht
<dateline> bekommt (falls vorhanden) den Standardeinzug
aber
<signed> enthält praktisch immer eine topographische Auszeichnung und die geht vor. Aber zu der Räumlichkeit/Topographie beim Element <signed> wollte Fabian mit dir, glaube ich, noch konferieren.

**Comment by thelfensdrfer** [comment]
> in der Synopse steht grün unterlegt

Ahh ok, dass hab ich übersehen. Dann werde ich erst einmal für alle genannten Elemente in der normalisierten Ansicht einen Einzug festlegen. Fabian und ich wollten am Wochenende sowieso noch einmal miteinander sprechen, dann können wir das direkt klären.
