### ISSUE TITLE
Absätze bei space Elementen

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#42]
![Screenshot from 2020-12-17 21-10-57](https://user-images.githubusercontent.com/699106/102539189-a5327780-40ad-11eb-9a31-ccfa8a134420.png)

Die PDF und diplomatische Ansicht unterscheiden sich hier https://familie-engels-briefe.de/briefe/005#diplomatic

Das liegt daran weil ich aktuell die Space Element als `inline-block` Elemente betrachte, was sie ja auch manchmal sind. Hier sieht das HTML aber ca so aus:

```
space
Eingerückter Text
space
Eingerückter Text
space
Eingerückter Text
```

Die Einrückung funktioniert auch, aber damit das gleich aussieht müsste ich hier vor dem Space einen Absatz einfügen. Das ist aber nicht überall der Fall. Das space Element ist hier aber auch nicht speziell gekennzeichnet:

```html
<span data-dim="horizontal" data-quantity="13" data-unit="chars" class="tei_space" style="width: 6.5rem;"></span>
```

**Comment by FabianEtling** [comment]
Hier sollte es aktuell lediglich bei der normalisierten Wiedergabe Probleme ergeben.

Im TEI ist ab der mit "dringenden..." beginnenden Zeile ein Weißraum angelegt. Für die diplomatische Ansicht sollten sich Umbruch und Einrückung damit korrekt erzeugen lassen (ungeachtet dessen, ob die "-Zeichen dann auch unter dem ':' stehen).

Hier müsste mit der philologischen Seite noch einmal abgestimmt werden, was hier eigentlich zu sehen und in dipl. und norm. Ansicht wiederzugeben ist. -> @urummel ?

Ggf. könnte man über eine Interpretation und TEI-Kodierung als Tabellenstruktur nachdenken.
