### ISSUE TITLE
Darstellung des Brieftypes in Briefübersicht

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#47]

**Comment by thelfensdrfer** [comment]
@urummel Der kommt aktuell tatsächlich aus den Daten, ich dachte es wäre ein Fehler das dort überall "Brief" auftaucht. Ich lese den Brieftyp aus dem `engels:doctype` Attribut aus.

Beispiel für Brief 008:

```xml
<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:v="http://exist-db.org/versioning" xmlns:engels="http://www.engels.uni-wuppertal.de" engels:doctype="letter" xml:id="fe.008" n="0.3.01" v:revision="15464" v:key="176e1b2491b3c68" v:path="/db/apps/exist101-engels/data/fe008.xml">
```

Der Wert ist in jedem Brief `letter`, oder ist das die falsche Stelle?

**Comment by urummel** [comment]
Der Typ des Dokuments (Brief, Entwurf...) ist im Element <sourceDesc> als Attributwert zu @n hinterlegt.

<sourceDesc n="brief.original">
 <msDesc>

 </msDesc>
</sourceDesc>

Hier findest du die Bezeichnung, die je nach Wert in der Titelzeile erscheinen soll:

n="brief.original"
Bezeichnung für die Titelzeile: (Brief)

n="brief.abschrift"
Bezeichnung für die Titelzeile: (Abschrift)

n="brief.kopie"
Bezeichnung für die Titelzeile: (Briefkopie)

n="entwurf.original"
Bezeichnung für die Titelzeile: (Entwurf)

n="memorandum.original"
Bezeichnung für die Titelzeile: (Memorandum)
