### ISSUE TITLE
Überarbeitung der Briefüberschrift auf der Detailseite

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#54]
Neue Überschrift: **ID** [alte Überschrift] ([Brieftyp])

Bei dem Brieftyp soll es einen Tooltip geben, falls der Brieftyp "Brief mit Beilage" lautet. In dem Fall soll die Beilage verlinkt werden.

@urummel Bedarf es hier eines Tooltips? Man könnte sonst auch statt *Brief mit Beilage* z.B. folgendes anzeigen:

`001 Luise Noot, Hagen, an eine unbekannte Freundin, 05. Januar 1791, Mittwoch (Brief mit Beilage: 004)` wobei hier die 004 ein ganz normaler Link zu dem Brief 004 wäre.

**Comment by thelfensdrfer** [comment]
@urummel Es müssen nicht nur die eigentlichen doctypes angepasst werden, sondern auch die Überschriften aus den Quelldateien. Aktuell sieht die Überschrift für Brief `001` (externe ID 002) z.B. so aus:

`002 Luise Noot, Hagen, an eine unbekannte Freundin, 05. Januar 1791, Mittwoch (Abschrift) (Brief)`

- `002` ist die von mir vergeben ID, die Brief ID lautet wie gesagt `001`.
- `Luise Noot, Hagen, an eine unbekannte Freundin, 05. Januar 1791, Mittwoch (Abschrift)` ist die original Überschrift
- `Brief` extrahiere ich aus dem doctype.

Auch wenn die doctypes aktuell noch nicht stimmen, muss ich den trotzdem hinten anhängen. Andernfalls könnte ich später kein Mouse-Over-Effekt, für z.B. Beilagen, anzeigen. Also müssen die doctypes auf jeden Fall aus den Überschriften raus. Den Titel bekomme ich übrigens von hier:

```xml
<TEI [...] engels:doctype="letter" xml:id="fe.008">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Henriette Siebel, Barmen, an Louise Noot, Düsseldorf, 02. Juni 1791, Donnerstag (Brief)</title>
            </titleStmt>
[...]
```

**Comment by urummel** [comment]
Ich weiß im Moment nicht, wie aktuell dieser Eintrag noch ist:

Die Überschrift auf der **Detailseite** wäre hiernach also statisch, übernommen aus 

<titleStmt>
                <title>Henriette Siebel, Barmen, an Louise Noot, Düsseldorf, 02. Juni 1791, Donnerstag (Brief)</title>
            </titleStmt>

und die Einträge in der Liste aller Briefe dynamisch.

In der provisorischen Website von Fabian war es genau umgekehrt. Das muss ich mir vergegenwärtigen.

Ich weiß im Moment nicht mehr, ob wir beim letzten Mal beschlossen hatten, dass das so bleibt. 

Wenn ja, müsste ich also in den Daten im Element <title> den Dokumenten-Typ tilgen. Oder stellen sich inzwischen andere Fragen zur Briefüberschrift auf der Detailseite?

**Comment by urummel** [comment]
Jetzt zur **Beilage**. Mit Beilage ist jeweils nicht ein anderer Brief gemeint, sondern einmal ein 

Zeitungsausschnitt (Brief 071) 

und einmal ein 
Erinnerungskärtchen (Brief 131)
https://familie-engels-briefe.uni-wuppertal.de:8443/facs/FE_131.7_21041817.pdf

Allerdings: Bisher ist **weder** innerhalb von <text> eine besondere Auszeichnung vorgesehen,  
– wir haben die Transkriptionen hilfsweise als 
`<div type="writing-session" n="2">`
deklariert und an den Brieftext angehängt –
**noch** ist im Header irgendeine Auszeichnung vorgesehen.

**Comment by thelfensdrfer** [comment]
> Die Überschrift auf der **Detailseite** wäre hiernach also statisch

In der Listenansicht gibt es ja keine Überschrift mehr. Und in der Detailseite ist die Überschrift jetzt dynamisch, so haben wir das auf jeden Fall letztens besprochen.

**Comment by thelfensdrfer** [comment]
Zu der Beilage sollten wir dann noch einmal einen gesonderten Issue aufmachen, können wir morgen gerne drüber sprechen!
