### ISSUE TITLE
Bezugsbriefe in Header auf Briefdetailseite

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#55]
Falls es einen vorausgegangen bzw. nachfolgenden Brief gibt, sollen diese im Header dargestellt werden. Hier fehlen aktuell aber noch die Quelldaten.

**Comment by urummel** [comment]
Ja, das stimmt, der Großteil der Daten dazu fehlt.

Aber so sieht es ggfs. in den Daten aus

<correspDesc>
                <...>
                <correspContext>
                    <ref type="prev" target="#fe.219">Gerhard Bernhard van Haar, Hamm, an Johann Caspar Engels sen., Barmen, 03. Oktober 1819</ref>
                    <ref type="next" target="#ID_NEXT_LETTER_OF_THIS_CORRESPONDENCE"/>
                </correspContext>
            </correspDesc> 

Das entscheidende ist die ID #fe.219 , die sich auf die  alte Nummerierung bezieht. Hier müsste natürlich die neue Nummer angezeigt werden.
Ließen sich hier die die einzelnen Bestandteile (Briefnummer, Schreiber, Schreiberort, Empfänger, Empfängerort, Datum, (Dokumententyp)) dynamisch anzeigen? Klar ist, dass der Wochentag bisher nur im <title> steht. Da bräuchten wir noch eine eigene Lösung.

**Comment by thelfensdrfer** [comment]
@urummel Ich habe jetzt zwei Button mit Pfeilen hinzugefügt. Diese werden nur angezeigt wenn das System auch Briefe für die ID in `target` findet. Da lässt sich später auf jeden Fall auch noch ein kleines Fenster für mehr Briefdetails einfügen,

**Comment by urummel** [comment]
Im Prinzip gut so.
Aber: Chrome (desktop + mobil), firefox, edge:
- die Pfeile werden angezeigt, aber nur, wenn man aus der Brief-Liste auf den Brief kommt,
- die Verlinkung klappt nicht: Pfeil ist clickbar, die Browser-Adresszeile ändert die Adresse korrekt, aber kein reload,
- ruft man die Seite dann aktiv, auf erscheint dort kein Pfeil (s.o. nur wenn man aus der Briefübersicht kommt).

**Comment by thelfensdrfer** [comment]
Das sollte gleich korrigiert sein.
