### ISSUE TITLE
Ergänzung der Hervorhebungen

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#56]
Neues Dropdown enthält:

* [x] Meta-Daten (Nur diplomatische Ansicht)
* [x] Normalisierungen (Änderungen die in der dipl. Darstellung nicht auftauchen - daher wird der Punkt dort auch ausgegraut)
* [x] Sachkommentar (das sind die Stellenerläuterungen)
* [x] Textkritische Annotationen (das sind die Annotationen)
* [x] Personen
* [x] Orte
* [x] Firmen
* [x] Themen (gibt es bereits)

**Comment by thelfensdrfer** [comment]
Anhang von Wolfgang Lukas:

```
1. Normalisierungen
2. Textkritische Kommentare
3. Sachkommentare
4. Personen
5. Firmen/Unternehmen
6. Orte
7. Thematische Erschließung
- Liebe/Ehe
- Religion
- Wirtschaft/Geschäftliches
- etc.

Aktive Anwählbarkeit:

- Nr. 1: nur in der normalisierten Ansicht, in der diplomat. ausgegraut
- Nr. 2: im Gegenzug nur in der diplomat. Ansicht, in der normalis. ausgegraut
- Nr. 3–7: nur in der normalisierten Ansicht. Die aktuelle Markierung (durch Unterstrichelung) soll bitte entfallen! (das war eigtl. so nie vorgesehen und würde ja auch mit dem Auswahlangebot kollidieren)

Prinzip: alle editorischen erschließenden bzw. annotierenden Leistungen werden in der normalisierten Ansicht angeboten, die damit als solche auch noch einmal legitimiert wird (Ausnahme: Nr. 2!)


Art der Hervorhebung:

- Nr. 1: in dem Maße, wie die Unterstrichelung, die wohl diskreteste Form der Markierung, frei wird, könnte man sie hierfür verwenden. Damit wird auch deutlich gemacht, dass diese Hervorhebng einen etwas anderen Status besitzt als die folgenden: dort gibt es i.d.R. einen Kommentar, hier nur die Markierung. Allerdings: Man könnte anstatt eines Kommentars jeweils den originalen Wortlaut als tooltip per mouseover zeigen (also etwa: „Glück“/[Glük]“). Das wäre schön, zumal wir ja die Möglichkeit einer direkten Gegenüberstellung der beiden Textansichten nicht vorsehen.
- Nr. 2–6: da sollte man jew. dieselbe Farbe (oder auch eine andere Art der Unterstreichung?) wählen: eine möglichst diskrete translucente Farbe, die nicht schon durch die Themen vergeben ist. Im Tooltip wird per mouseover jew. der Annotationstext eingeblendet.
- Nr. 7: wie gestern besprochen.

```

**Comment by thelfensdrfer** [comment]
Daten die normalerweise nicht im Brief zu finden sind, nur anzeigen wenn das entsprechende Element angeklickt wurde.

**Comment by thelfensdrfer** [comment]
Nur lexikalische Phänomene

**Comment by thelfensdrfer** [comment]
@urummel Ich bräuchte hier irgendeine Liste mit den möglichen Normalisierungen. Z.B. anhand der Nummern hier: https://static.familie-engels-briefe.de/erl/ERL_Synopse.htm

**Comment by urummel** [comment]
So?

1.10.1   Emendationen [d.h. eine Ergänzung im Text durch den Editor, deswegen ist das <orig/> leer]
<choice>
        <orig/>
        <corr type="emendation">eine</corr>
      </choice>

1.10.2   Normalisierung der Transkription
1.10.2.1    Orthografische Normalisierung [d.h. Anpassung der Rechtschreibung an den Stand der Rechtschreibregeln um 1800]
<choice>
  <orig>GebätsErhorung</orig>
  <corr type="ortho">Gebetserhörung</corr>
</choice>

1.10.2.2    Normalisierung von Interpunktionszeichen [z.B. bei ungewöhnlichen Abkürzungspunkten (':' statt korrekt '.')]
<choice>
    <orig><am>:</am></orig>
    <corr type="norm"><am>.</am></corr>
  </choice>

**Comment by thelfensdrfer** [comment]
Ja, genau. Also es reicht wenn du die Nummern aufschreibst bzw. auch zusammenfasst, z.B.: 1.10-1.19

**Comment by urummel** [comment]
Betreffende Gliederungspunkte in der Synopse 
https://static.familie-engels-briefe.de/erl/ERL_Synopse.htm

1. Normalisierungen --> 1.10.2 
2. Textkritische Kommentare --> 4.6.2
3. Sachkommentare --> 4.6.1
4. Personen --> 4.1
5. Firmen/Unternehmen --> 4.3 (=Organisationsnamen oder Verweise auf Organisationen)
6. Orte --> 4.2
7. Thematische Erschließung --> 4.7

**Comment by thelfensdrfer** [comment]
* [ ] Themen sollen invers markiert werden. Das heißt Alles außer die Themen selbst sollen ausgegraut werden
* [ ] Alles außer Normalisierung und Themen in blau markieren

**Comment by urummel** [comment]
Dies ist die Liste der Themen für die thematische Auszeichnung, nach der Herr Lukas codiert hat:

W Wirtschaft
R Religion
P Politik
G Gesundheit/Krankheit
E Erziehung
K Kultur (z. B. Musik, Literatur...)
EB Stadtgeschichte Elberfeld und Barmen (evtl. Engelskirchen)
H Engels-Haus/-Fabrik
M Mobilität/Reisen
B Bibel(zitate)
L Liebe
