### ISSUE TITLE
Marginaltext in diplomatischer Ansicht an korrekter Stelle einfügen

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#60]
Mit einem Rand zwischen Marginaltext und Fließtext?

**Comment by thelfensdrfer** [comment]
@urummel Ich bin hier auf der Suche nach einem Beispielbrief, hast du da zufällig einen parat?

**Comment by urummel** [comment]
z. B. Brief 64 (neue Nummerierung), S. 1. [das ist die Brief-ID #fe.071]
