### ISSUE TITLE
Textträgerbeschreibung immer unter Brief anzeigen

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#67]

**Comment by thelfensdrfer** [comment]
@urummel Wie werden die Metadaten im TEI codiert?

**Comment by urummel** [comment]
An verschiedenen Stellen: 
Bsp. Brief 001
"Schreiberhand", d.h. wer schreibt und mit welchem Schreibmaterial:
hier Johann Caspar Engels mit schwarzer Tinte. 

außerdem werden hier die verwendete Handschrift (Kurrent, Lateinisch) und ggfs. vorkommende Druckschriften deklariert.

`<sourceDesc n="brief.abschrift">
<...>
<physDesc>
<handDesc>
                            <handNote xml:id="g.rend.hand.default" n="default" scribeRef="#pers.partic.engels-johann-caspar-II">schwarze Tinte</handNote>
                            
                            <handNote scribeRef="#pers.partic.AAA-freundin-unknown" xml:id="rend.hand.bleistift">Bleistift</handNote>
                        </handDesc>
                       <typeDesc>
                            
                            <typeNote xml:id="g.rend.type.antiqua" n="default">gedruckter Text, in Antiqua gesetzt</typeNote>
                            <typeNote xml:id="g.rend.type.gothic">gedruckter Text, in gebrochener Schrift gesetzt</typeNote>
                            
                        </typeDesc>
                        <scriptDesc>
                            
                            <scriptNote xml:id="g.rend.script.latin">Handschrift, lateinische Schrift</scriptNote>
                            <scriptNote xml:id="g.rend.script.kurrent" n="default">Handschrift, deutsche Kurrentschrift</scriptNote>
                            
                        </scriptDesc>
<...>
</physDesc>
</sourceDesc>`

**Comment by urummel** [comment]
Die Informationen zum Archiv:
innerhalb von <sourceDesc>

`<msIdentifier>
                        <settlement>Wuppertal</settlement>
                        <repository>Stadtarchiv</repository>
                        <idno>[SIGNATUR]</idno>
                    </msIdentifier>`

**Comment by urummel** [comment]
Ich krieg' den Code nicht hübscher hin, sorry.

**Comment by urummel** [comment]
Die Texträgerbeschreibung (noch nicht eingepflegt):

Ebenfalls in der < sourceDesc > 

`
<msPart xml:id="bb1"> 
                        <msIdentifier>
                            <idno>bb1</idno>
                        </msIdentifier>
                        <physDesc>
                            
                            <ab type="misc"/>
                            
                            <objectDesc>
                                <supportDesc>
                                    <support>
                                        <material>[MATERIAL]</material>
                                        <watermark n="N"/>
                                        <note type="color">[FARBE]</note>
                                        <note type="processing" n="n"/>
                                    </support>
                                    <extent>
                                        <dimensions type="D" unit="mm">
                                            <width>[WIDTH]</width>
                                            <height>[HEIGHT]</height>
                                        </dimensions>
                                    </extent>
                                    <condition>
                                        <damage/>
                                    </condition>
                                </supportDesc>
                            </objectDesc>
                            
                            <handDesc>
                                <handNote>[SCHREIBMATERIAL]</handNote>
                            </handDesc>
                            <decoDesc>
                                <decoNote type="monogram" n="n"/>
                                <decoNote type="ruling" n="n"/>
                            </decoDesc>
                        </physDesc>
                    </msPart>
                </msDesc>`

Wir müssen noch die **Kategorien und Inhalte** liefern.

**Comment by thelfensdrfer** [comment]
> Ich krieg' den Code nicht hübscher hin, sorry.

Kein Problem. Hier gibt es in diesem Editor zwei Modi, ein Gravis (wieder etwas gelernt) markiert den Text als "Inline" und drei Gravis als "Block". Bei dem Block Format werden auch die Zeilenumbrüche angezeigt.
