### ISSUE TITLE
Vorschlag von WL: Platzhalter für bisher nicht ausgezeichnete Briefe

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#68]
WL schrieb am 5.2.2021 per E-Mail:

"Es fehlen ja noch einige Briefe – aber könnte man für diese evtl. Platzhalter einbauen, die indirekt mitzählen, damit dann im Gesamtkorpus die Nummerierung stimmt? Denn das stete Umrechnen-Müssen ist bei der Arbeit einfach mühsam und die korrekte Ordnung würde sehr viel Zeit sparen. Also, wenn das irgendwie möglich wäre, dass wir die definitive Reihung/Nummerierung hinbekommen, wäre das super."

Als erstes stelle ich eine Liste zusammen mit den Lücken, d. h. mit den fehlenden Briefen mit den wesentlichen Briefdaten. 

Dann müssen wir klären, ob und wie es funktionieren kann. Mit meinen etwas laienhaften Worten: Setzt du die Platzhalter im htlm um oder legen wir xml-Platzhalter-Dateien an?

**Comment by thelfensdrfer** [comment]
Das geht glaub ich nur wenn die Briefplatzhalter auch wirklich als XML vorliegen. Wenn die da sind muss ich aber noch einmal gründlich über die Seite gucken, ob nicht an manchen Stellen Fehler auftauchen, weil nicht alle Daten bei den Platzhaltern vorliegen.

**Comment by urummel** [comment]
OK, dann müssen wir die xml-Dateien rudimentär, aber sorgfältig anlegen.

**Comment by urummel** [comment]
Ich habe jetzt zu Testzwecken Brief xml:id="fe.147" als xml-File in der Datenbank angelegt. Ohne Text.

**Comment by urummel** [comment]
xml:id="fe.046" auch angelegt. Die weiteren Dateien folgen nach und nach.

**Comment by urummel** [comment]
Die Platzhalter sollen selbst nicht erscheinen (weder in der Briefliste noch in der Einzelansicht), aber die Nummerierung beeinflussen, damit die Briefe später auch korrekt nummeriert sind.

Diese noch **nicht ausgezeichneten Briefe** sind nicht zu verwechseln mit **erschlossenen Briefe**.

**Comment by thelfensdrfer** [comment]
TODO: Synchronisation funktioniert eventuell nicht?
