### ISSUE TITLE
Brief-Beilage in Überschrift verlinken

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#69]

**Comment by urummel** [comment]
'''<div type="writing-session" subtype="beilage" n="2" rendition="#g.rend.type.gothic">'''

**Comment by urummel** [comment]
```<div type="writing-session" subtype="beilage" n="2" rendition="#g.rend.type.gothic">```

**Comment by urummel** [comment]
Ich habe jetzt hilfsweise einen subtype "beilage" eingeführt, der keinen Fehler provoziert. Damit könnten wir Beilagen kennzeichnen. Darauf könnte der Link aus der Brief-Überschrift verlinken.

**Comment by thelfensdrfer** [comment]
Das wird leider im HTML noch nicht korrekt dargestellt, evtl. müsste Fabian das noch einmal geringfügig anpassen? 
![image](https://user-images.githubusercontent.com/699106/132120965-5b13f82b-deec-4c56-b954-d375afe9fdfb.png)

Im XML taucht es auf:
![image](https://user-images.githubusercontent.com/699106/132120982-80bd091d-1e7d-4e40-bae9-7acfc2c83105.png)

**Comment by thelfensdrfer** [comment]
@FabianEtling

**Comment by thelfensdrfer** [comment]
"mit Beilage"
