### ISSUE TITLE
Tag und Monat in Briefüberschrift in Detailansicht

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#70]
Tag und Monat werden nicht angezeigt in der Briefüberschrift in Detailansicht.

**Comment by thelfensdrfer** [comment]
Bei Briefen bei denen es ein vollständiges Datum gibt, z.B. 004, wird gleich das vollständige Datum in der Überschrift angezeigt.

**Comment by urummel** [comment]
Bei mir nicht. ???

**Comment by urummel** [comment]
Ah, **gleich**, tschuldigung!!!

**Comment by thelfensdrfer** [comment]
Das wollte ich gerade schreiben, genau ;)

Aber wichtig das wir das jetzt einmal klären, ich habe hier noch keine optimale Lösung gefunden. Das einspielen eines Updates auf dem Server dauert ca. 5-15 Minuten, daher mache ich das nicht immer nach jeder Änderung. Aber damit ich nicht mit den Issues durcheinander komme, hake ich die immer sofort ab. Mir ist aber durchaus bewusst das das dann bei anderen Personen die die Issues lesen zu Verwirrungen kommen kann. Aber vielleicht ist es auch genug wenn du darüber Bescheid weißt?
