### ISSUE TITLE
Einweisungszeichen überarbeiten

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#80]
* Andere Schriftart (Editorschriftart)
* Spiegeln (prüfen ob möglich)

**Comment by urummel** [comment]
Die Frage war noch offen, ob die Richtung der Einweisungszeichen unterscheidbar ist (im Code):
Nur mittelbar durch die Position: Steht das metamark **vor** dem einzuweisenden Text, zeigt das Einweisungszeichen nach rechts, steht es **hinter** dem einzuweisenden Text, zeigt es nach links.

**Comment by thelfensdrfer** [comment]
Möglich anhand `data-target` und `data-id`. Beispiel: https://familie-engels-briefe.de/briefe/001#diplomatisch
