### ISSUE TITLE
Textträgerbeschreibung

### ISSUE THREAD

**Issue by thelfensdrfer** [familie-engels-briefe/webapp#81]
* [x] Ausklappbar machen
* [x] Nur in der diplomatischen Ansicht anzeigen
* [x] Keinen Rahmen

**Comment by urummel** [comment]
Hallo Tim,

hier nun das Wording zu den Textträgerbeschreibungen.

[Texttraegerbeschreibung.pdf](https://github.com/familie-engels-briefe/webapp/files/6210137/Texttraegerbeschreibung.pdf)

Es war etwas komplizierter als gedacht, was sich auch im Ergebnis zeigt. Es kann sein, dass noch Kategorien dazu kommen. Das werden wir sehen, wenn die Daten eingepflegt sind.

Wir können darüber – falls nötig – ja noch gesondert konferieren.

Mit besten Grüßen
Ulrich
