### ISSUE TITLE
Anzeige Datum im Falle "invalid date" (z.B. Brief 009)

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#83]
Sortierung der Briefe ist korrekt entsprechend den Attributwerten:

z. B. Brief 009:

`<date notBefore="1791-06-03" notAfter="1791-06-04">Anfang Juni 1791</date>`

aber Fehler "invalid date" bzw. "NaN" in Liste aller Briefe bzw. Einzeldarstellung.

Lässt sich die natürlichsprachliche Datumsangabe in solchen Fällen eines nicht eindeutigen Datums aus dem plaintext im `<date>`-Element holen, also im Beispiel "Anfang Juni 1791"?

**Comment by thelfensdrfer** [comment]
Kannst du mir davon vielleicht einen Screenshot schicken? Ich sehe immer nur 1791?

**Comment by thelfensdrfer** [comment]
https://familie-engels-briefe.de/briefe/009#normalisiert
