### ISSUE TITLE
Zeilennummerierung/Zeilenzähler: Übersprungene Zeilen

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#95]
Bsp.: https://familie-engels-briefe.de/briefe/071#diplomatisch

Möglicherweise liegt das Überspringen von Zeilen beim Zählen an dieser Auszeichnung:

``<lb break="no" rendition="#g.enc.tagsdecl.hyphenation.colon"/>``

Sie dient dazu, dass in der normalisierten Ansicht mit aufgehobenem Zeilenumbruch kein Leerzeichen gesetzt wird. 

Vielleicht werden nur  "leere" ``<lb/>`` gezählt.

**Comment by thelfensdrfer** [comment]
Bei mir wird das glaub ich richtig angezeigt, oder?

![image](https://user-images.githubusercontent.com/699106/134641507-a32af902-2fa3-43ac-acf2-c4ec810e8a83.png)

Die Nummerierung fügt neue Zeilennummern aktuell bei folgenden Selektoren ein:

`[data-page="wrapper"] .tei_p`, 
`[data-page="wrapper"] .tei_lb`, 
`[data-page="wrapper"] .tei_opener`

Also aktuell geht das rein nach Klasse und es wird nicht auf den Inhalt oder andere Details geachtet.

**Comment by urummel** [comment]
Ja, das habe ich jetzt auch gesehen. Aber da war doch neulich noch die Zählung verschoben, oder? So stimmt es jetzt.
