### ISSUE TITLE
Zugang zur Website Svenja Hagenhoff und Julian Polberg

### ISSUE THREAD

**Issue by urummel** [familie-engels-briefe/webapp#96]
Ich bitte einfach auf diesem Wege um Zugangsdaten zur Website für die Kollegin Svenja und den Kollegen Julian:

svenja.hagenhoff@uni-wuppertal.de

julian.polberg@uni-wuppertal.de

Danke vielmals.

**Comment by thelfensdrfer** [comment]
Als Dokumentation: https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-nginx-on-ubuntu-14-04
